name: Docker

on:
  workflow_call:
    inputs:
      image-name:
        type: string
        description: Short name of the image, defaults to the repo name
        default: ${{ github.repository }}
      security-category:
        type: string
        default: ""
      push:
        type: string
        description: Docker push input
        default: 'true'
      dockerfile:
        type: string
        description: Dockerfile path
        default: Dockerfile
      context:
        type: string
        description: Dockerfile path
        default: .
      qemu-arm64:
        type: boolean
        description: Use QEMU for arm64
        default: false
      platforms:
        type: string
        description: Platforms to build
        default: linux/amd64,linux/arm64
      trivy:
        type: string
        description: Run Trivy vulnerability scanner
        default: 'true'
      build-args:
        type: string
        description: Docker build args
      version:
        type: string
        description: App version
        default: ""
      version-from-artifact:
        type: string
        description: App version from artifact name
        default: ""

jobs:
  docker-runners:
    uses: USA-RedDragon/reusable-actions/.github/workflows/docker-runners.yaml@v2.0.4
    if: ${{ inputs.qemu-arm64 == false }}
    with:
      image-name: ${{ inputs.image-name }}
      security-category: ${{ inputs.security-category }}
      push: ${{ inputs.push }}
      dockerfile: ${{ inputs.dockerfile }}
      context: ${{ inputs.context }}
      platforms: ${{ inputs.platforms }}
      build-args: ${{ inputs.build-args }}
      version: ${{ inputs.version }}
      version-from-artifact: ${{ inputs.version-from-artifact }}

  docker-qemu:
    uses: USA-RedDragon/reusable-actions/.github/workflows/docker-qemu.yaml@v2.0.4
    if: ${{ inputs.qemu-arm64 == true }}
    with:
      image-name: ${{ inputs.image-name }}
      security-category: ${{ inputs.security-category }}
      push: ${{ inputs.push }}
      dockerfile: ${{ inputs.dockerfile }}
      context: ${{ inputs.context }}
      platforms: ${{ inputs.platforms }}
      build-args: ${{ inputs.build-args }}
      version: ${{ inputs.version }}
      version-from-artifact: ${{ inputs.version-from-artifact }}

  docker:
    if: always()
    runs-on: ubuntu-24.04
    needs: [docker-runners, docker-qemu]
    steps:
      - name: Check at least one job succeeded
        run: |
          if [ "${{ needs.docker-runners.result }}" != "success" ] && [ "${{ needs.docker-qemu.result }}" != "success" ]; then
            echo "At least one of the jobs docker-runners or docker-qemu must succeed"
            exit 1
          fi
