name: Docker

on:
  workflow_call:
    inputs:
      image-name:
        type: string
        description: Short name of the image, defaults to the repo name
        default: ${{ github.repository }}
      security-category:
        type: string
        default: ""
      push:
        type: string
        description: Docker push input
        default: 'true'
      dockerfile:
        type: string
        description: Dockerfile path
        default: Dockerfile
      context:
        type: string
        description: Dockerfile path
        default: .
      platforms:
        type: string
        description: Platforms to build
        default: linux/amd64,linux/arm64
      build-args:
        type: string
        description: Docker build args
      version:
        type: string
        description: App version
        default: ""
      version-from-artifact:
        type: string
        description: App version from artifact name
        default: ""

jobs:
  docker:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        if: inputs.push == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version artifact
        if: inputs.version == '' && inputs.version-from-artifact != ''
        id: version-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.version-from-artifact }}
          path: /tmp

      - name: Determine version
        id: version
        run: |
          if [ -f /tmp/version ]; then
            echo "version=$(cat /tmp/version)" >> $GITHUB_OUTPUT
          else
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ inputs.image-name }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=${{ steps.version.outputs.version }},enable=${{ steps.version.outputs.version != '' }}
            type=semver,pattern=v{{version}},value=${{ steps.version.outputs.version }},enable=${{ steps.version.outputs.version != '' }}
            type=semver,pattern=v{{major}},value=${{ steps.version.outputs.version }},enable=${{ steps.version.outputs.version != '' }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ steps.version.outputs.version }},enable=${{ steps.version.outputs.version != '' }}
            type=semver,pattern=v{{version}},event=tag,enable=${{ steps.version.outputs.version == '' }}
            type=semver,pattern=v{{major}},event=tag,enable=${{ steps.version.outputs.version == '' }}
            type=semver,pattern=v{{major}}.{{minor}},event=tag,enable=${{ steps.version.outputs.version == '' }}
            type=semver,pattern={{version}},value=${{ steps.version.outputs.version }},enable=${{ steps.version.outputs.version != '' }}
            type=semver,pattern={{major}},value=${{ steps.version.outputs.version }},enable=${{ steps.version.outputs.version != '' }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.version.outputs.version }},enable=${{ steps.version.outputs.version != '' }}
            type=semver,pattern={{version}},event=tag,enable=${{ steps.version.outputs.version == '' }}
            type=semver,pattern={{major}},event=tag,enable=${{ steps.version.outputs.version == '' }}
            type=semver,pattern={{major}}.{{minor}},event=tag,enable=${{ steps.version.outputs.version == '' }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        id: docker_build
        with:
          context: ${{ inputs.context }}
          push: ${{ inputs.push }}
          pull: true
          provenance: mode=max
          sbom: true
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            ${{ inputs.build-args }}

      - name: Lowercase image name
        id: lowercase-image
        run: echo "IMAGE=${IMG,,}" >> $GITHUB_OUTPUT
        env:
          IMG: ${{ inputs.image-name }}

      - name: Run Trivy vulnerability scanner
        if: inputs.push == 'true'
        uses: aquasecurity/trivy-action@0.17.0
        with:
          image-ref: ghcr.io/${{ steps.lowercase-image.outputs.IMAGE }}@${{ steps.docker_build.outputs.imageid }}
          format: 'sarif'
          ignore-unfixed: true
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        if: inputs.push == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          category: ${{ inputs.security-category }}
