name: GoReleaser

on:
  workflow_call:
    inputs:
      docker-hub-username:
        type: string
        description: Docker Hub username
      extra-args:
        type: string
        description: Extra arguments to pass to GoReleaser
      beta:
        type: boolean
        description: Whether to release as a beta
        default: false
      setup-node:
        type: boolean
        description: Whether to set up Node.js
        default: false
      run-before:
        type: string
        description: Command to run before the release
        default: ''
    secrets:
      docker-hub-password:
        description: Docker Hub password
      token:
        description: GitHub token

jobs:
  goreleaser:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        if: inputs.setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.token }}

      - name: Log in to Docker Hub
        if: ${{ inputs.docker-hub-username != '' }}
        uses: docker/login-action@v1
        with:
          username: ${{ inputs.docker-hub-username }}
          password: ${{ secrets.docker-hub-password }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - if: ${{ inputs.run-before != '' }}
        name: Run before
        run: ${{ inputs.run-before }}

      - run: go generate ./...

      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean ${{ inputs.beta && '--snapshot' || '' }} ${{ inputs.extra-args }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

      - name: Push beta image
        if: inputs.beta
        run: |
          export REPO="$(tr '[[:upper:]]' '[[:lower:]]' <<< "ghcr.io/$GITHUB_REPOSITORY")"
          IMAGES=()
          while read -r SOURCE DEST; do
            docker tag "$SOURCE" "$DEST"
            docker push "$DEST"
            IMAGES+=("$DEST")
          done \
            < <(docker image ls --format=json | \
              yq --input-format=json --output-format=tsv '
                select(.Repository == strenv(REPO)) |
                [
                  .Repository + ":" + .Tag,
                  .Repository + ":beta-" + (.Tag | sub(".*-", ""))
                ]
              ')

          docker manifest create "$REPO:beta" "${IMAGES[@]}"
          docker manifest push "$REPO:beta"

      - uses: creekorful/goreportcard-action@v1.0
