name: Docker

on:
  pull_request:
  push:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  docker:
    uses: ./.github/workflows/docker-ci.yaml
    with:
      push: 'false'
      dockerfile: Dockerfile.test
      build-args: TEST_ARG=not
      context: test/docker
